import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {makeCase,orch,waitForStatus} from './helpers.mjs';
import {loadConfig} from '../src/config.mjs';
import {cmdPick} from '../src/ledger.mjs';
import {callTool} from '../src/mcp.mjs';
import {makeRepo,craftFinishedRun} from './wf-helpers.mjs';
/** @type {any} */
const routing=await import('../src/routing.mjs').catch(()=>({}));
const now=Date.parse('2026-01-10T12:00:00Z'),iso=new Date(now).toISOString();
function task(extra={}){assert.equal(typeof routing.validateTask,'function');return routing.validateTask({version:1,type:'helper',class:'C2',size:'S',risk:'standard',tools:['shell'],modalities:['text'],contextTokens:1000,capability:'coding',...extra});}
function profile(id='a',extra={}){return {id,cli:'opencode',harnessVersion:'1.0',model:'localai/'+id,role:'worker',account:'local',billing:'local',enabled:true,availability:{status:'available',checkedAt:iso},qualification:{status:'qualified',evidence:'trial-'+id},capability:'coding',supports:{types:['helper','auth','migration','race','visual','review','feature'],classes:['C2','C3','C4'],risks:['standard','critical'],tools:['shell','read'],modalities:['text','image'],contextTokens:8000},costRank:0,latencyRank:0,...extra};}
function policy(profiles=[profile('a'),profile('b')],extra={}){assert.equal(typeof routing.validateRoutingPolicy,'function');return routing.validateRoutingPolicy({version:1,catalogVersion:'fixture-1',availabilityMaxAgeMinutes:60,preference:'rotation',profiles,...extra});}
function decide(extra={}){const p=extra.policy??policy();return routing.selectRouting({policy:p,task:task(),role:'worker',candidates:p.profiles.map(p=>({cli:p.cli,model:p.model,runs:0,same_family:false})),roster:p.profiles.map(p=>({cli:p.cli,model:p.model,family:p.id})),implementerModels:[],quota:{enabled:false},now,...extra});}

test('P05a distinguishes complexity from size and records selected exact profile',()=>{const d=decide({task:task({class:'C4',size:'XS',type:'race'})});assert.equal(d.status,'selected');assert.equal(d.profile.id,'a');assert.equal(d.task.class,'C4');assert.equal(d.task.size,'XS');assert.equal(d.catalogVersion,'fixture-1');});
test('task-fit filters tools, context and visual input before rotation',()=>{const p=policy([profile('a',{supports:{...profile().supports,contextTokens:500,modalities:['text']}}),profile('b')]);const d=decide({policy:p,task:task({type:'visual',class:'C3',modalities:['image'],contextTokens:2000})});assert.equal(d.profile.id,'b');assert.match(d.profiles[0].reasons.join(' '),/context|modalities/);});
test('a broad C label cannot qualify different task requirements',()=>{const p=policy([profile('a',{supports:{...profile().supports,types:['feature']}})]);assert.equal(decide({policy:p}).status,'no-eligible-route');});
test('qualified mode refuses research candidates; qualification mode is explicit',()=>{const p=policy([profile('a',{qualification:{status:'unqualified',evidence:null}})]);assert.equal(decide({policy:p}).status,'no-eligible-route');assert.equal(decide({policy:p,mode:'qualification'}).status,'selected');});
test('disabled profiles never become qualified trial routes',()=>{assert.equal(decide({policy:policy([profile('a',{enabled:false})]),mode:'qualification'}).status,'no-eligible-route');});
test('missing, stale and future availability cannot manufacture usable routes',()=>{for(const availability of [{status:'unknown',checkedAt:null},{status:'available',checkedAt:new Date(now-3600001).toISOString()},{status:'available',checkedAt:new Date(now+1).toISOString()}])assert.equal(decide({policy:policy([profile('a',{availability})])}).status,'availability-unknown');});
test('critical auth and migration reviews require C4 and a different model family',()=>{const p=policy([profile('a',{role:'reviewer',supports:{...profile().supports,classes:['C3']}}),profile('b',{role:'reviewer'})]);const d=decide({policy:p,role:'reviewer',task:task({type:'auth',class:'C3'}),implementerModels:['localai/a']});assert.equal(d.task.risk,'critical');assert.equal(d.requiredClass,'C4');assert.equal(d.profile.id,'b');assert.match(d.profiles[0].reasons.join(' '),/C4|family/);});
test('critical review cannot fall back to same family under exhaustion',()=>{const p=policy([profile('a',{role:'reviewer'})]);assert.equal(decide({policy:p,role:'reviewer',task:task({risk:'critical'}),implementerModels:['a-other'],roster:[{model:'a-other',family:'same'},{model:'a',family:'same'}]}).status,'no-eligible-route');});
test('canonical implementer identity is refused across harness aliases',()=>{const p=policy([profile('a',{role:'reviewer'})]);assert.equal(decide({policy:p,role:'reviewer',implementerModels:['A']}).status,'no-eligible-route');});
test('C0 formatting reports action-required without selecting or executing a model',()=>{const d=decide({task:task({type:'format',class:'C0'})});assert.equal(d.status,'action-required');assert.equal(d.profile,null);});
test('task validation rejects lowering critical demand and malformed requirements',()=>{for(const changes of [{type:'auth',class:'C2'},{type:'race',class:'C3'},{contextTokens:-1},{tools:['read','read']},{class:'C0',type:'helper'},{risk:'unknown'}])assert.throws(()=>task(changes));});
test('policy rejects ambiguous execution routes, API billing and cloud unmetered declarations',()=>{for(const profiles of [[profile(),profile('b',{model:'localai/a'})],[profile('a',{billing:'api'})],[profile('a',{cli:'codex',billing:'local'})],[profile('a',{qualification:{status:'qualified',evidence:null}})]])assert.throws(()=>policy(profiles));});
test('existing roster exclusions cannot be re-enabled by profiles',()=>{const d=decide({candidates:[]});assert.equal(d.status,'no-eligible-route');assert.ok(d.profiles.every(p=>p.reasons.includes('excluded by roster eligibility')));});
test('subscription execution profiles need compatible quota account bindings',()=>{const p=policy([profile('a',{cli:'codex',billing:'subscription',account:'account-a'})]);assert.equal(decide({policy:p}).status,'availability-unknown');});
test('owner cost preference breaks eligible local ties while rotation remains the default',()=>{const profiles=[profile('a',{costRank:20}),profile('b',{costRank:5})];assert.equal(decide({policy:policy(profiles)}).profile.id,'a');assert.equal(decide({policy:policy(profiles,{preference:'cost'})}).profile.id,'b');});

export {now,task,profile,policy};
test('a bound profile cannot claim qualification after caller changes launch selectors',async t=>{const s=disk(t);for(const changed of [{effort:'high'},{agent:'different-agent'},{flag:['--different-setting']}])await assert.rejects(routing.prepareRoutingLaunch({args:{...s.args,...changed,profile:'a'},cfg:loadConfig(s.c.stateRoot),cli:'opencode',model:'localai/a',role:'worker'}),{code:'routing-deferred'});});

test('rotation tie preserves the existing roster order rather than policy order',()=>{const p=policy();assert.equal(decide({policy:p,candidates:[{cli:'opencode',model:'localai/b',runs:0},{cli:'opencode',model:'localai/a',runs:0}]}).profile.id,'b');});
test('critical family independence cannot be inferred from unknown roster families',()=>{const p=policy([profile('a',{role:'reviewer'})]);assert.equal(decide({policy:p,role:'reviewer',task:task({risk:'critical'}),implementerModels:['other'],roster:[]}).status,'no-eligible-route');});
test('local adapter size limit holds even if a roster candidate claims a cloud lane',()=>{assert.equal(decide({task:task({size:'M'})}).status,'no-eligible-route');});

function cloudQuota(remaining=[80,80]){
  const profiles=['a','b'].map((id,i)=>profile(id,{cli:i?'vibe':'codex',billing:'subscription',account:id}));
  const pools=['a','b'].map(id=>({id,key:id.repeat(64),ignore:{},windows:[{id:'session',unit:'percent',controller:5,review:10,retry:5,warn:25,models:[]}]}));
  return {profiles,quota:{enabled:true,policy:{pools,localRoutes:[],routes:profiles.map(p=>({cli:p.cli,model:p.model,role:'worker',pool:p.account,capability:'coding',costs:{session:{XS:5,S:10,M:20}}}))},leases:[],usage:{pools:pools.map((p,i)=>({id:p.id,billing:'subscription',freshness:'fresh',error:null,observation:{bindingVerified:true,observedAt:iso,windows:[{id:'session',kind:'quota',unit:'percent',remaining:remaining[i],limit:100,durationMinutes:100,resetsAt:new Date(now+(i?90:10)*60000).toISOString(),models:[],freshness:'fresh'}]}}))}}};
}
test('quota pace outranks owner cost preference among task-qualified subscriptions',()=>{const {profiles,quota}=cloudQuota();profiles[0].costRank=100;const d=decide({policy:policy(profiles,{preference:'cost'}),quota});assert.equal(d.profile.id,'a');assert.equal(d.quota.allocationMode,'reset-cycle');});
test('quota alternative cannot lower task-specific capability and exhausted fit routes defer',()=>{const {profiles,quota}=cloudQuota([10,80]);profiles[1].supports.tools=[];const d=decide({policy:policy(profiles),quota});assert.equal(d.status,'quota-deferred');assert.equal(d.profile,null);});
test('profile account mismatch cannot spend another quota binding',()=>{const {profiles,quota}=cloudQuota();profiles[0].account='different';const d=decide({policy:policy([profiles[0]]),quota});assert.equal(d.status,'availability-unknown');});
test('explicit retry reserve class reaches the P08 selection service',()=>{const {profiles,quota}=cloudQuota([25,0]);assert.equal(decide({policy:policy(profiles),quota}).status,'quota-deferred');assert.equal(decide({policy:policy(profiles),quota,purpose:'retry'}).status,'selected');});

function disk(t,profiles=[profile('a')]){
  const c=makeCase('routing-p05a');t.after(()=>c.cleanup());
  profiles.forEach(p=>p.availability.checkedAt=new Date().toISOString());
  const routingFile=path.join(c.base,'routing.json'),taskFile=path.join(c.base,'task.json'),rosterFile=path.join(c.base,'roster.json');
  fs.writeFileSync(routingFile,JSON.stringify({version:1,catalogVersion:'fixture-1',availabilityMaxAgeMinutes:60,preference:'rotation',profiles}));
  fs.writeFileSync(taskFile,JSON.stringify(task()));
  fs.writeFileSync(rosterFile,JSON.stringify({models:profiles.map(p=>({cli:p.cli,model:p.model,family:p.id,lane:p.billing==='local'?'local':'cloud',workloads:['implement','review']}))}));
  return {c,routingFile,taskFile,rosterFile,args:{_:[],'routing-policy':routingFile,task:taskFile,roster:rosterFile,workload:'implement',size:'S'}};
}
test('CLI and MCP expose identical cached task-fit decisions without enabling owner config',async t=>{const s=disk(t);const cli=await orch(['pick','--workload','implement','--size','S','--routing-policy',s.routingFile,'--task',s.taskFile,'--roster',s.rosterFile,'--json'],s.c.env);assert.equal(cli.code,0,cli.stderr);const json=JSON.parse(cli.stdout);assert.equal(json.pick.profile,'a');const {_:unused,...mcpArgs}=s.args;const mcp=await callTool('pick',mcpArgs,{stateRoot:s.c.stateRoot});assert.equal(mcp.isError,false,mcp.content[0].text);const parsed=JSON.parse(mcp.content[0].text);assert.equal(parsed.pick.profile,'a');assert.deepEqual(parsed.routing,json.routing);});
test('bound mismatched launch is refused before worker/adapter side effects',async t=>{const s=disk(t);delete s.c.env.ORCH_LANE_ID;const r=await orch(['run','--cli','opencode','--model','localai/other','--dir',s.c.work,'--handoff',s.c.handoffPath,'--no-window','--routing-policy',s.routingFile,'--task',s.taskFile,'--profile','a','--roster',s.rosterFile,'--json'],s.c.env);assert.equal(r.code,2);assert.match(r.stderr,/match.*profile/);assert.equal(fs.readdirSync(path.join(s.c.stateRoot,'runs')).length,0);});
test('conflicting task size or capability is not silently rewritten',async t=>{const s=disk(t);for(const changes of [{size:'M'},{capability:'other'}])await assert.rejects(cmdPick(loadConfig(s.c.stateRoot),{...s.args,...changes},{log(){}}),{code:'bad-routing-task'});});
test('routing mode off preserves the legacy pick output',async t=>{const s=disk(t);const result=await cmdPick(loadConfig(s.c.stateRoot),{_:[],workload:'implement',size:'S',roster:s.rosterFile,json:true},{log(){}});assert.equal(result.pick.model,'localai/a');assert.equal('routing' in result,false);});
test('critical review launch refuses same family before creating a reviewer package',async t=>{const s=disk(t,[profile('a',{role:'reviewer'})]);const repo=path.join(s.c.base,'repo'),head=makeRepo(repo,{'a.txt':'fixture\n'});const impl=craftFinishedRun(s.c.stateRoot,{dir:repo,baseline:head,allow:['a.txt'],extra:{model_requested:'a-other',model_canonical:'a-other',size:'S'}});const roster=JSON.parse(fs.readFileSync(s.rosterFile,'utf8'));roster.models.push({cli:'opencode',model:'a-other',family:'a',lane:'local',workloads:['implement']});fs.writeFileSync(s.rosterFile,JSON.stringify(roster));fs.writeFileSync(s.taskFile,JSON.stringify(task({risk:'critical'})));const root=path.join(s.c.base,'reviews');const r=await orch(['review','--run',impl,'--ref',head,'--reviewer','opencode','--model','localai/a','--prompt',s.c.handoffPath,'--by','codex','--review-root',root,'--routing-policy',s.routingFile,'--task',s.taskFile,'--profile','a','--roster',s.rosterFile,'--json'],s.c.env);assert.equal(r.code,2,r.stderr);assert.match(r.stderr,/different model family/);assert.equal(fs.existsSync(root),false);});

test('subscription launch records routing plus atomic quota provenance after fresh admission',async t=>{
  const s=disk(t,[profile('a',{cli:'fake',model:'a-model',billing:'subscription',account:'a'})]);
  const values=path.join(s.c.base,'values.json'),usageFile=path.join(s.c.base,'usage.json'),quotaFile=path.join(s.c.base,'quota.json');
  fs.writeFileSync(values,JSON.stringify({remaining:80}));
  fs.writeFileSync(usageFile,JSON.stringify({version:1,pools:[{id:'a',provider:'fixture',account:'personal',workspace:'default',billing:'subscription',collector:{kind:'json',command:process.execPath,args:[path.resolve('test/fixtures/quota-helper.mjs'),values],version:'1',source:'json',accountFingerprint:'a'.repeat(64)}}],bindings:[{id:'worker',role:'worker',harness:'fake',model:'a-model',pool:'a'}]}));
  fs.writeFileSync(quotaFile,JSON.stringify({version:1,usageConfig:'usage.json',stateRoot:'shared-quota',pools:[{id:'a',windows:[{id:'session',unit:'percent',controller:5,review:10,retry:5,warn:25}]}],routes:[{binding:'worker',capability:'coding',costs:{session:{XS:5,S:10,M:20}}}]}));
  const r=await orch(['run','--cli','fake','--model','a-model','--dir',s.c.work,'--handoff',s.c.handoffPath,'--no-window','--routing-policy',s.routingFile,'--task',s.taskFile,'--profile','a','--roster',s.rosterFile,'--quota-policy',quotaFile,'--json'],s.c.env);assert.equal(r.code,0,r.stderr);const out=JSON.parse(r.stdout);assert.equal(out.routing.profile,'a');assert.equal(out.quota.pool,'a');const record=JSON.parse(fs.readFileSync(path.join(s.c.stateRoot,'runs',out.id,'run.json'),'utf8'));assert.deepEqual(record.routing,out.routing);await waitForStatus(s.c.stateRoot,out.id,['completed','failed'],{timeoutMs:30000});
});
